# Generated by Django 3.2.4 on 2021-10-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_drfmodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfmodel',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
